export interface NigerianState {
  name: string;
  cities: string[];
}

export const NIGERIAN_STATES: NigerianState[] = [
  {
    name: "Abia",
    cities: [
      "Aba",
      "Abiriba",
      "Agbala",
      "Akwete",
      "Alayi",
      "Amaeke",
      "Amaozara",
      "Amawom",
      "Amuvi",
      "Ariam Ala-Ala",
      "Arochukwu",
      "Awomukwu",
      "Azumini",
      "Ekwelu",
      "Eluoma",
      "Igbere",
      "Ikwuano",
      "Isiala Oboro",
      "Isuikwuato",
      "Mgboko Ngwa",
      "Ndi Elu Nkporo",
      "Ndoro",
      "Nkpa",
      "Nsirimo",
      "Obi Ngwa",
      "Obinkita",
      "Ohafia",
      "Ohanze",
      "Osisioma Ngwa",
      "Ovukwu",
      "Owerrinta",
      "Ubakala",
      "Ugwunagbo",
      "Umu-Nneochi",
      "Umuahia",
      "Umudike",
      "Umukabia",
      "Uturu",
    ],
  },
  {
    name: "Adamawa",
    cities: [
      "Alkalawa",
      "Bakari Bata",
      "Belel",
      "Demsa",
      "Dumne",
      "Fufore",
      "Gangkombol",
      "Ganye",
      "Girei",
      "Gombi",
      "Guyuk",
      "Hong",
      "Jada",
      "Jimeta",
      "Karna Magna",
      "Lamurde",
      "Laoukobong",
      "Madagali",
      "Maiha",
      "Mayo Lope",
      "Mayo-Banyo",
      "Mayo-Belwa",
      "Mbere",
      "Mbondjanga",
      "Meiganga",
      "Michika",
      "Mubi",
      "Mugulbu",
      "Ngaoundere",
      "Ngaouyanga",
      "Numan",
      "Shelleng",
      "Shuwa",
      "Song",
      "Toukouroua",
      "Tungo",
      "Yola",
    ],
  },
  {
    name: "Akwa Ibom",
    cities: [
      "Abak",
      "Afaha",
      "Ediene",
      "Eket",
      "Ekparakwa",
      "Ekpene Ukim",
      "Eman",
      "Esit Eket",
      "Essien Udim",
      "Etim Ekpo",
      "Etinan",
      "Ibeno",
      "Ibesikpo Asutan",
      "Ibiaku",
      "Ibiono Ibom",
      "Idu",
      "Ika",
      "Ikono",
      "Ikot Abasi",
      "Ikot Afanga",
      "Ikot Ekpene",
      "Ikot Nta",
      "Ikot Okoro",
      "Ikot Onwon",
      "Ikot Udo",
      "Ini",
      "Itu",
      "Mbo",
      "Mkpat Enin",
      "Nsit Ibom",
      "Nsit Ubium",
      "Ntak Ibesit",
      "Obio Ndobo",
      "Obolo",
      "Obot Akara",
      "Okobo",
      "Onna",
      "Oron",
      "Oruk Anam",
      "Otung",
      "Oyubia",
      "Oyuko Ibighi",
      "Ubodung",
      "Udung Uko",
      "Ukanafun",
      "Uruan",
      "Usuk Obio Ediene",
      "Uyo",
    ],
  },
  {
    name: "Anambra",
    cities: [
      "Abagana",
      "Abatete",
      "Adazi Nnukwu",
      "Aguata",
      "Aguleri",
      "Agulu",
      "Akpu",
      "Alor",
      "Amawbia",
      "Anaocha",
      "Atani",
      "Awgbu",
      "Awka",
      "Awka Etiti",
      "Awkuzu",
      "Ebenebe",
      "Ekwulobia",
      "Enugwu Aguleri",
      "Enugwu Ukwu",
      "Ezinifite",
      "Ezira",
      "Ideani",
      "Igbo Ukwu",
      "Ihembosi",
      "Ihiala",
      "Ihite",
      "Nanka",
      "Nawfia",
      "Nawfija",
      "Neni",
      "Nibo",
      "Nimo",
      "Nkpor",
      "Nnewi",
      "Nsugbe",
      "Nzam",
      "Oba",
      "Obosi",
      "Ogbunka",
      "Ogidi",
      "Omashi",
      "Onitsha",
      "Oraukwu",
      "Osumenyi",
      "Otuocha",
      "Ozubulu",
      "Uga",
      "Ukwulu",
      "Umuleri",
    ],
  },
  {
    name: "Bauchi",
    cities: [
      "Alkaleri",
      "Azare",
      "Bauchi",
      "Bogoro",
      "Damban",
      "Darazo",
      "Dass",
      "Disina",
      "Faggo",
      "Foggo",
      "Gamawa",
      "Ganjuwa",
      "Giade",
      "Jamaare",
      "Katagum",
      "Kirfi",
      "Misau",
      "Ningi",
      "Shira",
      "Tafawa Balewa",
      "Toro",
      "Warji",
      "Zadawa",
      "Zaki",
    ],
  },
  {
    name: "Bayelsa",
    cities: [
      "Brass",
      "Ekeremor",
      "Nembe",
      "Ogbia",
      "Oloibiri",
      "Otuoke",
      "Sagbama",
      "Yenagoa",
    ],
  },
  {
    name: "Benue",
    cities: [
      "Agbadi",
      "Buruku",
      "Gboko",
      "Guma",
      "Igumale",
      "Katsina Ala",
      "Konshisha",
      "Kwande",
      "Logo",
      "Makurdi",
      "Obagaji",
      "Obi",
      "Ogbadibo",
      "Ohimini",
      "Okpokwu",
      "Otukpa",
      "Otukpo",
      "Tarka",
      "Ukum",
      "Ushongo",
      "Vande Ikya",
      "Yala",
    ],
  },
  {
    name: "Borno",
    cities: [
      "Bama",
      "Bayo",
      "Biu",
      "Bornu Yassu",
      "Chibok",
      "Damasak",
      "Damboa",
      "Dikwa",
      "Doro Gowon",
      "Gambaru",
      "Gubio",
      "Guzamala",
      "Gwoza",
      "Hawul",
      "Jere",
      "Kaga",
      "Kareto",
      "Kauwa",
      "Kogu",
      "Kukawa",
      "Kwaya Kusar",
      "Mafa",
      "Magumeri",
      "Maiduguri",
      "Mandaragirau",
      "Marte",
      "Mobbar",
      "Ngala",
      "Nganzai",
      "Ngurno",
      "Rann",
      "Shani",
    ],
  },
  {
    name: "Cross River",
    cities: [
      "Ababene",
      "Abi",
      "Adadama",
      "Afafanyi",
      "Akpap",
      "Bamba",
      "Calabar",
      "Ediba",
      "Epenti",
      "Esuk Otu",
      "Idomi",
      "Inyima",
      "Mkpani",
      "Ugep",
    ],
  },
  {
    name: "Delta",
    cities: [
      "Abo",
      "Agbarho",
      "Asaba",
      "Bomadi",
      "Burutu",
      "Ekakpamre",
      "Ekrejegbe",
      "Emede",
      "Emevor",
      "Enwe",
      "Igbodo",
      "Igbuku",
      "Igbuzor",
      "Illah",
      "Obiaruku",
      "Ofagbe",
      "Ogbe-Ijoh",
      "Oghara",
      "Ogwashi-Ukwu",
      "Onicha-Ugbo",
      "Onogboko",
      "Oyede",
      "Ubulu-uku",
      "Udu",
      "Ughelli",
      "Utagba Ogbe",
    ],
  },
  {
    name: "Ebonyi",
    cities: [
      "Abakaliki",
      "Amaigbo",
      "Amaozara",
      "Ebonyi",
      "Ishiagu",
      "Ishieke",
      "Ishielu",
      "Nkalagu",
      "Ntezi-Aba",
      "Ohaozara",
      "Onicha",
      "Unwana",
    ],
  },
  {
    name: "Edo",
    cities: [
      "Aboudou",
      "Afuze",
      "Agenebode",
      "Akoko-Edo",
      "Auchi",
      "Benin City",
      "Egor",
      "Ekpoma",
      "Esan Central",
      "Etsako Central",
      "Ewohimi",
      "Ewu-Esan",
      "Ibilo",
      "Ibore",
      "Iguegben",
      "Ihievbe",
      "Ikpoba-Okha",
      "Imiekuri",
      "Irrua",
      "Iyamho",
      "Jattu",
      "Obadan",
      "Ohordua",
      "Okada",
      "Okpekpe",
      "Okpella",
      "Oredo",
      "Orhionmwon",
      "Ososo",
      "Ugboha",
      "Ughoton",
      "Uhunmwonde",
      "Uokha",
      "Urhonigbe",
      "Uromi",
      "Uzairue",
      "Uzebba",
    ],
  },
  {
    name: "Ekiti",
    cities: [
      "Ado Ekiti",
      "Ado-Ekiti",
      "Efon",
      "Efon Alaaye",
      "Emure",
      "Erinmope Ekiti",
      "Gbonyin",
      "Ido Ekiti",
      "Ido-Osi",
      "Ijare",
      "Ijero",
      "Ijurin",
      "Ikere",
      "Ikole",
      "Ikoro",
      "Ilawe Ekiti",
      "Ilejemeje",
      "Ire Ekiti",
      "Ise",
      "Iyin",
      "Moba",
      "Oke-Mesi",
      "Okemesi",
      "Omuo",
      "Oye",
    ],
  },
  {
    name: "Enugu",
    cities: [
      "Abi",
      "Abor",
      "Achi",
      "Agbani",
      "Aku",
      "Aninri",
      "Awgu",
      "Eha Amufu",
      "Enugu",
      "Enugu Inyi",
      "Enugu-Ezike",
      "Ezeagu",
      "Igbo-Etiti",
      "Ikolo",
      "Isi-Uzo",
      "Mmaku",
      "Ngwo",
      "Nomeh Unateze",
      "Nru Nsukka",
      "Nsukka",
      "Obimo",
      "Ohum",
      "Oji River",
      "Okpogho",
      "Owo",
      "Ozara",
      "Udenu",
      "Udi",
      "Ugbo",
      "Ugwueme",
      "Ugwuoba",
      "Ukobu",
      "Umudim",
      "Umulokpa",
      "Uzo-Uwani",
    ],
  },
  {
    name: "Federal Capital Territory",
    cities: [
      "Abuja",
      "Asokoro",
      "Bwari",
      "Dutse Alhaji",
      "Galadima",
      "Galadimawa",
      "Garki",
      "Gui",
      "Gwagwa",
      "Gwarinpa",
      "Jiwa",
      "Karshi",
      "Karu",
      "Kubwa",
      "Nyanya",
      "Orozo",
      "Wuse",
    ],
  },
  {
    name: "Gombe",
    cities: [
      "Akko",
      "Bajoga",
      "Balanga",
      "Billiri",
      "Deba Habe",
      "Dukku",
      "Funakaye",
      "Gamadadi",
      "Gombe",
      "Gujuba",
      "Gwandum",
      "Kaltungo",
      "Kwami",
      "Nafada",
      "Shinga",
      "Shomgom",
      "Tukulma",
      "Tumu",
    ],
  },
  {
    name: "Imo",
    cities: [
      "Abajah",
      "Abba",
      "Agbala",
      "Akabo",
      "Akalovo",
      "Amaebu Ogwa",
      "Amaifeke",
      "Amaimo",
      "Amakohia",
      "Amatta",
      "Amike",
      "Amuro",
      "Anara",
      "Dikenafai",
      "Egbu",
      "Ehime - Mbano",
      "Ekwereazu",
      "Emii",
      "Ezeoke Nsu",
      "Eziama Obiato",
      "Ihiagwa",
      "Iho",
      "Ikembara",
      "Isuobiangwu",
      "Itu",
      "Izombe",
      "Mbieri",
      "Naze",
      "Nkwesi",
      "Obilokwu Mbieri",
      "Obinze",
      "Obodo",
      "Obodoukwu",
      "Ogbaku",
      "Oguta",
      "Ohoba",
      "Okwele",
      "Okwudor",
      "Orodo",
      "Osina",
      "Otulu",
      "Owelu",
      "Owerri",
      "Ozara",
      "Ubomiri",
      "Umu Oma",
      "Umuchima",
      "Umueshi",
      "Umukabia",
      "Umunoha",
      "Umunumo",
    ],
  },
  {
    name: "Jigawa",
    cities: [
      "Amaryawa",
      "Auyo",
      "Biriniwa",
      "Birnin Kudu",
      "Buji",
      "Dutse",
      "Fagam",
      "Gagarawa",
      "Garki",
      "Guri",
      "Gwaram",
      "Gwiwa",
      "Hadejia",
      "Jahun",
      "Kafin Hausa",
      "Katanga",
      "Kaugama",
      "Kazaure",
      "Kiri Kasama",
      "Kiyawa",
      "Maigatari",
      "Malam Maduri",
      "Miga",
      "Ringim",
      "Roni",
      "Sule Tankarkar",
      "Taura",
    ],
  },
  {
    name: "Kaduna",
    cities: [
      "Antan",
      "Atuku",
      "Birnin Gwari",
      "Chikun",
      "Damakasuwa",
      "Geshere",
      "Gidan Waya",
      "Giwa",
      "Gwanki",
      "Idon",
      "Igabi",
      "Ikara",
      "Jere",
      "Kachia",
      "Kaduna",
      "Kafanchan",
      "Kagarko",
      "Kagoro",
      "Kajuru",
      "Kamuru",
      "Kaura",
      "Kauru",
      "Kubacha",
      "Kudaru",
      "Kwoi",
      "Lere",
      "Makarfi",
      "Malagum",
      "Manchok",
      "Rahama",
      "Rigacikun",
      "Sabon Gari",
      "Samaru",
      "Saminaka",
      "Sanga",
      "Soba",
      "Tudun Wada",
      "Zangon Kataf",
    ],
  },
  {
    name: "Kano",
    cities: [
      "Ajingi",
      "Albasu",
      "Bagwai",
      "Bebeji",
      "Bichi",
      "Bunkure",
      "Dambatta",
      "Dawakin Kudu",
      "Dawakin Tofa",
      "Doguwa",
      "Gabasawa",
      "Garko",
      "Garum Mallam",
      "Gaya",
      "Gezawa",
      "Gwanki",
      "Gwarzo",
      "Kabo",
      "Kano",
      "Karaye",
      "Kibiya",
      "Kiru",
      "Kumbotso",
      "Kunchi",
      "Kura",
      "Madobi",
      "Makoda",
      "Minjibir",
      "Rano",
      "Rimin Gado",
      "Rogo",
      "Shanomo",
      "Sumaila",
      "Takai",
      "Tamburawa",
      "Tofa",
      "Tsanyawa",
      "Tudun Wada",
      "Ungogo",
      "Warawa",
      "Wudil",
    ],
  },
  {
    name: "Katsina",
    cities: [
      "Bakori",
      "Batagarawa",
      "Batsari",
      "Baure",
      "Bindawa",
      "Charanchi",
      "Dan Musa",
      "Dandume",
      "Danja",
      "Daura",
      "Dutsi",
      "Dutsin-Ma",
      "Faskari",
      "Funtua",
      "Girka",
      "Ingawa",
      "Jibia",
      "Kafur",
      "Kaita",
      "Kankara",
      "Kankia",
      "Katsina",
      "Kurfi",
      "Kusada",
      "Maiadua",
      "Malumfashi",
      "Mani",
      "Mashi",
      "Matazu",
      "Musawa",
      "Rimi",
      "Sabuwa",
      "Safana",
      "Sandamu",
      "Zango",
    ],
  },
  {
    name: "Kebbi",
    cities: [
      "Aleiro",
      "Aliero",
      "Arewa Dandi",
      "Augi",
      "Baguda",
      "Bena",
      "Bin Yauri",
      "Birnin Kebbi",
      "Bunza",
      "Dandi",
      "Fakai",
      "Gwandu",
      "Illo",
      "Jega",
      "Kalgo",
      "Maiyama",
      "Ngaski",
      "Sakaba",
      "Shanga",
      "Suru",
      "Yelwa",
      "Zuru",
    ],
  },
  {
    name: "Kogi",
    cities: [
      "Adavi",
      "Aiyetoro Gbede",
      "Ajaokuta",
      "Amuro",
      "Ankpa",
      "Ayegunle",
      "Bassa",
      "Dekina",
      "Egbe",
      "Ejule",
      "Ekinrin-Adde",
      "Ibaji",
      "Idah",
      "Igalamela-Odolu",
      "Ijagbe",
      "Ijumu",
      "Illah Bunu",
      "Isanlu",
      "Itakpe",
      "Iyah Gbede",
      "Kabba",
      "Lokoja",
      "Mopa",
      "Mopa-Muro",
      "Obajana",
      "Ofu",
      "Ogaminana",
      "Ogidi",
      "Okehi",
      "Okene",
      "Okenyi",
      "Olamaboro",
      "Omala",
    ],
  },
  {
    name: "Kwara",
    cities: [
      "Ajasse Ipo",
      "Alla Isin",
      "Aran-Orin",
      "Arandun",
      "Babanloma",
      "Baruten",
      "Buari",
      "Edidi",
      "Edu",
      "Ekiti",
      "Erin Ile",
      "Esie",
      "Ifelodun",
      "Igbonla",
      "Ijara Isin",
      "Iji Isin",
      "Ilala",
      "Iloffa",
      "Ilorin",
      "Isanlu Isin",
      "Iwo Isin",
      "Jebba",
      "Kaiama",
      "Kajola",
      "Lafiagi",
      "Moro",
      "Offa",
      "Oke Ero",
      "Oke Onigbin",
      "Okuta",
      "Omu-Aran",
      "Omupo",
      "Owa Onire",
      "Oyun",
      "Pamo Isin",
      "Pategi",
    ],
  },
  {
    name: "Lagos",
    cities: [
      "Adamo",
      "Agbede",
      "Agbowa Ikosi",
      "Agege",
      "Agric",
      "Aja",
      "Ajegunle",
      "Akesan",
      "Amuwo Odofin",
      "Ayobo",
      "Badagry",
      "Bariga",
      "Boundary",
      "Ebute",
      "Elepe",
      "Epe",
      "Festac",
      "Ikeja",
      "Ikorodu",
      "Ilaje",
      "Irewe",
      "Isiu",
      "Iyana Ipaja",
      "Ketu",
      "Kosofe",
      "Maryland",
      "Ogolonto",
      "Ojo",
      "Orile",
      "Somolu",
    ],
  },
  {
    name: "Nasarawa",
    cities: [
      "Ado",
      "Akwanga",
      "Alizaga",
      "Doma",
      "Gidan Mangoro",
      "Karshi",
      "Keana",
      "Keffi",
      "Kokona",
      "Lafia",
      "Laminga",
      "Loko",
      "Mararaba",
      "Masaka",
      "Nasarawa",
      "Nassarawa Egon",
      "New Nyanya",
      "Obi",
      "Toto",
      "Umaish",
      "Wamba",
    ],
  },
  {
    name: "Niger",
    cities: [
      "Bida",
      "Kontagora",
      "Minna",
      "Suleja",
    ],
  },
  {
    name: "Ogun",
    cities: [
      "Abeokuta",
      "Agbede",
      "Agbon",
      "Ago-Iwoye",
      "Atan",
      "Ayetoro",
      "Ewekoro",
      "Idiroko",
      "Idogo",
      "Ifo",
      "Ifonyintedo",
      "Igbesa",
      "Ijebu Igbo",
      "Ijebu Itele",
      "Ijebu Ode",
      "Ijoko",
      "Iju",
      "Ikenne",
      "Ilara-Ogudo Yewa",
      "Ilaro",
      "Imagbon",
      "Imeko Afon",
      "Iperu",
      "Ipokia",
      "Ishara",
      "Isonyin",
      "Ita Egbe",
      "Itori",
      "Iwoye",
      "Lisa",
      "Mobalufon",
      "Mowe",
      "Odeda",
      "Odogbolu",
      "Ogere",
      "Ogun waterside",
      "Oru",
      "Ota",
      "Owode",
      "Sagamu",
      "Wasinmi",
    ],
  },
  {
    name: "Ondo",
    cities: [
      "Akungba",
      "Akure",
      "Erusu",
      "Ese Odo",
      "Ibule-Soro",
      "Idanre",
      "Idoani",
      "Ifedore",
      "Ifon",
      "Igbara Oke",
      "Ijare",
      "Ikare",
      "Ilaje",
      "Ilara-Mokin",
      "Ipele",
      "Ipogun",
      "Irele",
      "Isarun",
      "Odigbo",
      "Oka Akoko",
      "Okitipupa",
      "Ondo",
      "Ose",
      "Owo",
      "Oyin",
      "Supare Akoko",
      "Ugbo Kingdom",
    ],
  },
  {
    name: "Osun",
    cities: [
      "Aiyedire",
      "Apomu",
      "Asipa",
      "Ayegunle",
      "Bode-Osi",
      "Boluwaduro",
      "Boripe",
      "Ede",
      "Egbedore",
      "Ejigbo",
      "Esa Oke",
      "Eti-Oni",
      "Gbongan",
      "Ibokun",
      "Ife",
      "Ifon-Osun",
      "Igbajo",
      "Ijebu Jesa",
      "Ikeji-Arakeji",
      "Ikire",
      "Ikirun",
      "Ila Odo",
      "Ilesa",
      "Ilobu",
      "Imesi-Ile",
      "Ipetu Ijesa",
      "Iragberi",
      "Iragbiji",
      "Irepodun",
      "Irewole",
      "Isokan",
      "Iwo",
      "Modakeke",
      "Ode Omu",
      "Odo Otin",
      "Ola Oluwa",
      "Orolu",
      "Osogbo",
      "Osu",
      "Otan Ayegbaju",
    ],
  },
  {
    name: "Oyo",
    cities: [
      "Ado Awaiye",
      "Afijio",
      "Ajegunle",
      "Akinyele",
      "Alaidan",
      "Asipa",
      "Atisbo",
      "Bara",
      "Egbeda",
      "Eruwa",
      "Ibadan",
      "Ibarapa",
      "Ido",
      "Igangan",
      "Igbeti",
      "Igbo-Ora",
      "Igboho",
      "Iseyin",
      "Iwajowa",
      "Kajola",
      "Kishi",
      "Lagelu",
      "Lalupon",
      "Ogbomoso",
      "Ogo Oluwa",
      "Okeho",
      "Olorunsogo",
      "Ona ara",
      "Orelope",
      "Ori Ire",
      "Oyo",
      "Saki",
      "Sepeteri",
      "Shaki",
      "Surulere",
    ],
  },
  {
    name: "Plateau",
    cities: [
      "Barkin Ladi",
      "Bassa",
      "Bokkos",
      "Ganawuri",
      "Gindiri",
      "Jengre",
      "Jos",
      "Kanam",
      "Kanke",
      "Kurgwi",
      "Langtang",
      "Mangu",
      "Mikang",
      "Pankshin",
      "Qua'an Pan",
      "Riyom",
      "Shendam",
      "Wase",
    ],
  },
  {
    name: "Rivers",
    cities: [
      "Akuku Toru",
      "Andoni",
      "Asari-Toru",
      "Degema",
      "Eleme",
      "Emelego",
      "Emuoha",
      "Etche",
      "Igwuruta",
      "Kono",
      "Oduoha-Emuoha",
      "Ogu Bolo",
      "Okrika",
      "Omumma",
      "Oyigbo",
      "Port Harcourt",
      "Rumuigbo",
    ],
  },
  {
    name: "Sokoto",
    cities: [
      "Balle",
      "Binji",
      "Bodinga",
      "Dange-Shuni",
      "Gada",
      "Gidan Madi",
      "Goronyo",
      "Gudu",
      "Gwadabawa",
      "Illela",
      "Isa",
      "Kebbe",
      "Kware",
      "Makwa",
      "Rabah",
      "Sabon Birni",
      "Shagari",
      "Silame",
      "Sokoto",
      "Tambuwal",
      "Tangaza",
      "Tureta",
      "Wamako",
      "Wurno",
      "Yabo",
    ],
  },
  {
    name: "Taraba",
    cities: [
      "Ardo-Kola",
      "Donga",
      "Dorofi",
      "Garin Kunini",
      "Gashaka",
      "Gassol",
      "Gembu",
      "Ibi",
      "Jalingo",
      "Karim Lamido",
      "Lau",
      "Muri",
      "Nguroje",
      "Sardauna",
      "Takum",
      "Ussa",
      "Wukari",
      "Yorro",
      "Zing",
    ],
  },
  {
    name: "Yobe",
    cities: [
      "Barde",
      "Borsari",
      "Buni Yadi",
      "Damaturu",
      "Dapchi",
      "Fika",
      "Fune",
      "Geidam",
      "Gujba",
      "Gulani",
      "Gwio Kura",
      "Jakusko",
      "Karasuwa",
      "Machina",
      "Nangere",
      "Nguru",
      "Tarmua",
      "Yunusari",
      "Yusufari",
    ],
  },
  {
    name: "Zamfara",
    cities: [
      "Anka",
      "Bagega",
      "Bakura",
      "Bukkuyum",
      "Bungudu",
      "Gummi",
      "Gusau",
      "Kaura Namoda",
      "Maradun",
      "Maru",
      "Shinkafi",
      "Talata Mafara",
      "Tsafe",
      "Zurmi",
    ],
  },
];
