-- Migration: Add 'cancelled' to the booking_status enum
--
-- getUserBookings selects inArray(booking.status, ["confirmed", "cancelled"])
-- to surface cancelled bookings alongside confirmed ones. That literal
-- fails at runtime with `invalid input value for enum booking_status:
-- "cancelled"` until the enum carries the value, so the read path and the
-- schema change have to ship together.
--
-- Nothing writes this value yet -- cancellation is currently recorded on
-- trip.status -- so the addition is forward-looking. It is needed now only
-- so the query parses.
--
-- Numbered 0041 because 0040_trip_dispatch.sql is numbered 0040 on this
-- branch. 0040 no longer touches booking_status, so this file is the only
-- place the value is added. It must still be applied BEFORE
-- 0042_booking_status_confirmed_only.sql, which removes it again.
--
-- Apply via `railway connect Postgres` (autocommit per statement). A value
-- added here cannot be used in the same transaction, which does not apply
-- to this migration as written.

ALTER TYPE "booking_status" ADD VALUE IF NOT EXISTS 'cancelled';